//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Variables
{
	// Shared Variables
	public String TERRAIN_NAME = "Default.png";
	public String DATA = "Age";
	public String SOURCE = "Victoria";
	public String TERRAIN_TYPE = "Smooth";
	public String PRESET = "Peaks";
	public float HEIGHTMAP_SIZE = 512f;
	public float COLORMAP_SIZE = 512f;
	public float SCALE_Y = 1f;
	public String FILENAME = "/Heightmaps/Vic_Data/r_acc_age_grid_VicAll-256x256.csv";
	public string MAP_FILENAME = "/Heightmaps/Maps/VicAll.png";
	public float MIN_X, MIN_Z, MAX_X, MAX_Z;
	public String COLOR_PRESET = ColorSpectrumObj.PRESET_GWR;
	public int COLUMN_X = 3;
	public int COLUMN_Y = 1;
	public int COLUMN_Z = 2;
	public string COLUMN_X_ALIAS = "X Axis";
	public string COLUMN_Y_ALIAS = "Y Axis";
	public string COLUMN_Z_ALIAS = "Z Axis";

	// Hills Variables ONLY
	public float MAX_RADIUS = 300f;
	public float ITERATION_NUMBER = 1000f;

	//Genetic Algorithm Variables ONLY
	public int GENETIC_MAX_ITERATION = 100;
	public int GENETIC_SMOOTH_ITERATION = 30;

	public Variables ()
	{
	}
}
